/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stock.maintaince.and.billing.system;
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author vishal
 */
public class login extends javax.swing.JFrame implements globalvariables {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setTitle("Login System\n");
        setPreferredSize(new java.awt.Dimension(450, 400));
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(230, 160, 189, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("PASSWORD");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 160, 130, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("USERNAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 130, 130, 23);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(230, 130, 189, 23);

        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(190, 200, 120, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock/maintaince/and/billing/system/images/login2.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 450, 380);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      try
      {
          Connection myconnection;
          myconnection=DriverManager.getConnection(PATH+PLACE,USERNAME,PASSWORD);
          try
          {
              String a="select*from logintable where username=? and password=?";
              PreparedStatement mystatement=myconnection.prepareStatement(a);
              mystatement.setString(1, jTextField1.getText());
              mystatement.setString(2, jPasswordField1.getText());
              ResultSet myresult=mystatement.executeQuery();
              if(myresult.next())
              {
                if(myresult.getString("usertype").equals("Admin"))
                {
                    parentframe obj=new parentframe();
                    obj.setVisible(true);
                    obj.setExtendedState(MAXIMIZED_BOTH);
                }
                else if(myresult.getString("usertype").equals("Employee"))
                {
                    parentframe2 obj=new parentframe2();
                    obj.setVisible(true);
                    obj.setExtendedState(MAXIMIZED_BOTH);
                }
                this.dispose();

             }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Wrong Username/password ");
            }
           }
           catch(Exception e)
            {
               JOptionPane.showMessageDialog(rootPane, "Error in Query " + e.getMessage());
            }
            finally
            {
                myconnection.close();
            }
    }
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
    }
                      
                   
          
          
      
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
