/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stock.maintaince.and.billing.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static stock.maintaince.and.billing.system.globalvariables.PASSWORD;
import static stock.maintaince.and.billing.system.globalvariables.PATH;
import static stock.maintaince.and.billing.system.globalvariables.PLACE;
import static stock.maintaince.and.billing.system.globalvariables.USERNAME;

/**
 *
 * @author vishal
 */
public class stockspurchased extends javax.swing.JInternalFrame  implements globalvariables{

    /**
     * Creates new form stockssold
     */
    public stockspurchased() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("TOTAL STOCKS PURCHASED");

        jLabel1.setText("FROM DATE");

        jLabel2.setText("TO DATE");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BILL NUMBER", "DATE", "PRODUCT TYPE", "PRODUCT NAME", "MANUFACTURER", "TOTAL COST"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("SHOW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setText("TOTAL PURCHASE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(287, 287, 287))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 919, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jButton1)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

if(jDateChooser2.getDate()!=null&&jDateChooser1.getDate()!=null)
 {
        try   
     {
            Connection myconnection;
            myconnection=DriverManager.getConnection(PATH+PLACE,USERNAME,PASSWORD);
            try
            {
               
              
              String query2="select * from purchasetable,product_detail where purchasetable.bill_no=product_detail.bill_no and  dateofpurchase between ? and ? "; 
              PreparedStatement mystatement2=myconnection.prepareStatement(query2);
                SimpleDateFormat obj=new SimpleDateFormat("yyyy-MM-dd");
     
      String date1=obj.format(jDateChooser1.getDate());
        String date2=obj.format(jDateChooser2.getDate());
              mystatement2.setString(1,date1);
              mystatement2.setString(2,date2);
    
              ResultSet myresult2=mystatement2.executeQuery();
             DefaultTableModel mymodel=(DefaultTableModel) jTable1.getModel();
                 mymodel.setRowCount(0);
              if(myresult2.next())
              {
               do
               {
                   String billno=myresult2.getString("bill_no");
               String date=myresult2.getString("dateofpurchase");
                   String ptype=myresult2.getString("producttype");
                   String pname=myresult2.getString("productname");
                   String manu=myresult2.getString("manufacturer");
                   String cost=myresult2.getString("totalcost");
                   //
                   mymodel.addRow(new Object[]{billno,date,ptype,pname,manu,cost});
               }
                 while(myresult2.next());
              } 
                  else
                  {
                     JOptionPane.showMessageDialog(rootPane, "No Records Found.");
                          
                  }
               int total=0,net=0;
        int r = jTable1.getRowCount();

        DefaultTableModel mymodel1=(DefaultTableModel) jTable1.getModel();
        for (int i = 0; i < r; i++)
        {

            total=Integer.parseInt(jTable1.getValueAt(i,5).toString());
            net += total;

        }

        jTextField1.setText("Rs."+String.valueOf(net));
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane,"Error in Query "+e.getMessage());
            }
            finally
            {
                myconnection.close();
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,"Error in Connection "+e.getMessage());
        }
 }
 else
 {
       JOptionPane.showMessageDialog(rootPane,"Please Enter A Valid Date");
 
//       Connection myconnection;
//            try
//            {
//                myconnection=DriverManager.getConnection(PATH+PLACE,USERNAME,PASSWORD);
//                    try
//                    {
//                        String a="select sum(quantity) from bill_details,bill_generation where date between ? and ?";
//                        PreparedStatement mystatement=myconnection.prepareStatement(a); 
//                        mystatement.setString(1, jDateChooser1.getDate().toString());
//                        mystatement.setString(1, jDateChooser2.getDate().toString());
//                        ResultSet myresult=mystatement.executeQuery();
//                        if(myresult.next())
//                        {
//                            do
//                            {
//                                String ptype,pname,manufacturer,price,quantity;
//                                ptype=myresult.getString("producttype");
//                                pname=myresult.getString("productname");
//                                manufacturer=myresult.getString("manufacturer");
//                                quantity=myresult.getString("manufacturer");
//             
//                                //int totalquantity=Double.parseDouble(price)*Integer.parseInt(quantity1);
//                            }while(myresult.next());
//                        }
//                        else
//                        {
//                            JOptionPane.showMessageDialog(rootPane, "No Recors found");
//                        }
//                        
//                    }
//                    catch(Exception e)
//                    {
//                        JOptionPane.showMessageDialog(rootPane, "Error in query " + e.getMessage());
//                    }
//                    finally
//                    {
//                        myconnection.close();
//                    }
//
//            }
//            catch(Exception e)
//            {
//                    JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
//            }
    }//GEN-LAST:event_jButton1ActionPerformed
    }
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
